<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student_data[
<!ELEMENT student_data (student*)>
<!ELEMENT student ( name , class , age )>
<!ELEMENT name (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST student id CDATA "ID_st1">
<!ATTLIST student id CDATA "ID_st2">
<!ATTLIST student id CDATA "ID_st3">
<!ENTITY class "12">
 ]>



<student_data>
<student id="ID_st1">
<name>Hafsa</name>
<class>10</class>
<age>17</age>
</student>
<student id="ID_st2">
<name>Areesha</name>
<class> &class; </class>
<age>21</age>
</student>
<student id="ID_st3">
<name>Waniya</name>
<class>10</class>
<age>15</age>
</student>
</student_data>